### ISSUE TITLE
Question: Word Segmentation standard  [Wisesight Samples with Word Tokenization Label]

### ISSUE THREAD

**Issue by c4n** [PyThaiNLP/wisesight-sentiment#5]
#### Questions
1. It would be nice to know what word segmentation standard was used to annotate this dataset.
2. How is the word segmentation standard used in this dataset different from other Thai corpora? (e.g., BEST, ORCHID)  
3. Is there any part of this dataset where annotators disagree with each other?

#### Files
[word tokenization samples](https://github.com/PyThaiNLP/wisesight-sentiment/tree/master/word-tokenization)

**Comment by p16i** [comment]
**Question**
1: We use [Aj.Wirote's criteria][criteria] which is looking at compositionality  of each word candidate. We split each part until segmentation yields a different meaning.

2: I'm not sure about this part either. Maybe we should look at it more closely, surveying what datasets we have and what a segmentation standard was used in each one.

3: Although we have two annotators, one of them performs a last revision. There might be some disagreements, caused by overlooking, but it should be rare. It would be good if other people help revise the dataset as well.

[criteria]: https://medium.com/@wirotearoonmanakun/การตัดคำภาษาไทย-ตัดคำอย่างไร-86b007fb648c

**Comment by c4n** [comment]
thank you! @heytitle
